server:
  port: 8082
  error:
    include-message: always
    include-binding-errors: always

spring:
  datasource:
    password: root
    url: jdbc:mysql://localhost:3306/inventoryService
    username: root
  jpa:
    hibernate:
      ddl-auto: create-drop
      proprties:
        hibernate:
          dialect: org.hibernate.dialect.Mysql5Dialect
          format_sql: true
      show-sql: true

