server:
  port: 8081
  error:
    include-message: always
    include-binding-errors: always

spring:
  application:
    name: order-service
  datasource:
    password: root
    url: jdbc:mysql://localhost:3306/orderService
    username: root
  jpa:
    hibernate:
      ddl-auto: update
      proprties:
        hibernate:
          dialect: org.hibernate.dialect.Mysql5Dialect
          format_sql: true
      show-sql: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:password@localhost:8761/eureka