server:
  port: 8081
  error:
    include-message: always
    include-binding-errors: always

spring:
  datasource:
    password: root
    url: jdbc:mysql://localhost:3306/orderService
    username: root
  jpa:
    hibernate:
      ddl-auto: update
      proprties:
        hibernate:
          dialect: org.hibernate.dialect.Mysql5Dialect
          format_sql: true
      show-sql: true
