server:
  port: 8081
  error:
    include-message: always
    include-binding-errors: always

spring:
  application:
    name: order-service
  datasource:
    password: root
    url: jdbc:mysql://localhost:3306/orderService
    username: root
  jpa:
    hibernate:
      ddl-auto: update
      proprties:
        hibernate:
          dialect: org.hibernate.dialect.Mysql5Dialect
          format_sql: true
      show-sql: true
  sleuth:
    sampler:
      probability: 1.0
  zipkin:
    base-url: http://localhost:9411

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:password@localhost:8761/eureka


management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

#Resilience4j properties
resilience4j:
  circuitbreaker:
    instances:
      inventory:
        registerHealthIndicator: true
        event-consumer-buffer-size: 10
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 5s
        permittedNumberOfCallseInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
  timelimiter:
    instances:
      inventory:
        timout-duration: 3s
  retry:
    instances:
      inventory:
        max-attempts: 3
        wait-duration: 5s



