server:
  port: 0
  error:
    include-message: always
    include-binding-errors: always

spring:
  application:
    name: inventory-service
  datasource:
    password: root
    url: jdbc:mysql://localhost:3306/inventoryService
    username: root
  jpa:
    hibernate:
      ddl-auto: create-drop
      proprties:
        hibernate:
          dialect: org.hibernate.dialect.Mysql5Dialect
          format_sql: true
      show-sql: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka